dist: trusty
sudo: false

language: python

matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36

install: pip install tox numpy pandas

script:
    - tox

deploy:
    provider: script
    skip_cleanup: true
    script:
        - pip install twine
        - python setup.py sdist bdist_wheel --universal
        - twine upload dist/* -u $TWINE_USER -p $TWINE_PASS
    on:
        tags: true
