matrix:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      language: python
      python: "3.6"
      sudo: false
      before_install:
          - sudo apt-get install -y graphviz
      dist: trusty
      deploy:
        skip_cleanup: true
        provider: script
        script: make publish
        on:
          tags: true
          repo: amphibian-dev/toad

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
          - brew install python3 graphviz

    - name: "Python 3.7.3 on Windows"
      os: windows
      language: sh
      python: "3.7"
      install:
          - choco upgrade chocolatey
          - choco install python3
          - choco install graphviz
          - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
          - python3 -m pip install --upgrade pip
          - pip3 install numpy pytest Cython
          - pip3 install -e .
  allow_failures:
    - os: windows

install:
    - pip3 install numpy pytest Cython
    - pip3 install -e .
script:
    - python3 -m pytest ./tests

before_deploy:
    - pip3 install wheel setuptools twine

deploy:
  skip_cleanup: true
  provider: script
  script: make publish_wheel
  on:
    tags: true
    repo: amphibian-dev/toad
