matrix:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      language: python
      python: "3.6"
      sudo: false
      before_install:
          - sudo apt-get install -y graphviz
      dist: trusty
      before_deploy:
          - make dist

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      env:
          - PYTHON=python3
          - PIP=pip3
      before_install:
          - brew install python3 graphviz
      before_deploy:
          - make dist_wheel

    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      python: "3.7"
      env:
          - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
          - choco install python
          - choco install graphviz
          - choco install make
      before_deploy:
          - make dist_wheel

    - name: "Python 3.6.3 on Windows"
      os: windows
      language: shell
      python: "3.6"
      env:
          - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
          - choco install python --version 3.6.8
          - choco install graphviz
          - choco install make
          - pip install -U patsy
      before_deploy:
          - make dist_wheel

  allow_failures:
    - os: windows

install:
    - make install
script:
    - make test

deploy:
  skip_cleanup: true
  provider: script
  script: make upload
  on:
    tags: true
    repo: amphibian-dev/toad
